name: Site testing

on: [push, pull_request]

jobs:
  pre_commit:
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  # vale:
  #   name: runner / vale
  #   needs: pre_commit
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: errata-ai/vale-action@reviewdog
  #       env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # with:
        #   files: workshops/

  test_build:
    name: Build site with no warnings
    needs: pre_commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      ##### Install required Python Modules and build the website #####
      - run: pip install -r requirements.txt
      - run: pip install git+https://${{ secrets.MKDOCS_INSIDER_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git@8.5.11-insiders-4.27.0
      - run: mkdocs build --strict
